apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-inference-gateway.fullname" . }}
  labels:
    {{- include "ai-inference-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.ANTHROPIC_API_KEY | quote }}
